server:
  port: 7001
  servlet:
    contextPath: /api

spring:
  application:
    name: drool-management-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  config:
    import: optional:file:.env.${spring.profiles.active}[.properties]
